# engine: gcsim
engine: wfpsim
# engine: wfpsim-custom
# engine: custom

# character to read char_dps from and (optionally) override main stats for.
# If omitted, main_stats will be ignored and personal_dps will not be output.
char: fischl

# Name of the roster (used in the output filename):
# output/grow_roster/<YYYYMMDD>_grow_roster_<char>_<roster_name>.xlsx
roster_name: grow_example

# supported: personal_dps|char_dps, team_dps
target:
  - personal_dps
  # - team_dps

# levels of investment are represented as substat optimizer option presets.
# options will be passed to engine CLI via -options "k=v;k2=v2".
investment_levels:
  - name: kqms
    options:
      total_liquid_substats: 20
      indiv_liquid_cap: 10
      fixed_substats_count: 2
  - name: high
    options:
      total_liquid_substats: 30
      indiv_liquid_cap: 12
      fixed_substats_count: 1
  - name: hyper
    options:
      total_liquid_substats: 40
      indiv_liquid_cap: 15
      fixed_substats_count: 0

# variants of main stats; cross product sands x goblet x circlet.
# if you omit main_stats entirely, grow_roster will not override main stats in config.txt.
main_stats:
  sands:
    # - er=0.518
    # - em=187
    - atk%=0.466
    # - hp%=0.466
    # - def%=0.466
  goblet:
    # - em=187
    # - atk%=0.466
    # - hp%=0.466
    # - def%=0.466
    - electro%=0.466
    # - pyro%=0.466
    # - hydro%=0.466
    # - cryo%=0.466
    # - anemo%=0.466
    # - geo%=0.466
    # - dendro%=0.466
    # - phys%=0.466
  circlet:
    # - em=187
    - cr=0.311
    - cd=0.622
    # - atk%=0.466
    # - hp%=0.466
    # - def%=0.466
    # - heal=0.359
